/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef BLUETOOTH_AUTODEFS_H
#define BLUETOOTH_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_BLUETOOTH_NAME "bluetooth"
#define S3E_EXT_BLUETOOTH_HASH 0x57ee47bb

#endif /* !BLUETOOTH_AUTODEFS_H */
